project_id = "work-home"

[api]
enabled = true
port = 55321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 55322
shadow_port = 55320
major_version = 17
health_timeout = "2m"

[db.pooler]
enabled = false
port = 55329

[db.migrations]
enabled = true
schema_paths = []

[db.seed]
enabled = false

[db.network_restrictions]
enabled = true
allowed_cidrs = ["127.0.0.0/8"]
allowed_cidrs_v6 = ["::1/128"]

[realtime]
enabled = false

[studio]
enabled = false
port = 55323

[local_smtp]
enabled = false
port = 55324

[storage]
enabled = false

[auth]
enabled = false

[edge_runtime]
enabled = false
inspector_port = 8183

[analytics]
enabled = false
port = 55327

[experimental.pgdelta]
enabled = false
